# Generated by Django 3.0.5 on 2024-10-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherExtra',
            new_name='Officestaff',
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_history', to='school.StudentExtra')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('pay_duedate', models.DateField()),
                ('payment_method', models.CharField(choices=[('card', 'CARD'), ('cash', 'CASH'), ('upi_transfer', 'UPI TRANSFER')], default='cash', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_history', to='school.StudentExtra')),
            ],
        ),
    ]
