# Generated by Django 3.0.5 on 2024-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20241025_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='borrow_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
