# Generated by Django 3.0.5 on 2024-10-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20241025_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
