# Generated by Django 3.0.5 on 2024-10-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20241026_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
