# Generated by Django 3.0.5 on 2024-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20241026_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentextra',
            old_name='first_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='fees',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='librarian',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
