# Generated by Django 3.0.5 on 2024-10-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_fees_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='student',
        ),
    ]
