# Generated by Django 3.0.5 on 2024-10-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20241026_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='user',
        ),
    ]
